export const urlGetEmpleado = "http://localhost:3000/empleado/"
export const urlGetReservas = "http://localhost:3000/reserva/"
export const urlGetNotas = "http://localhost:3000/notasInternas/"
export const urlGetHabitaciones = "http://localhost:3000/habitacion/"
export const urlPostAddEmpleado = "http://localhost:3000/empleado/crear"
export const urlPostAddReserva = "http://localhost:3000/reserva/crear"
export const urlPostAddNota = "http://localhost:3000/notasInternas/crear"
export const urlPostAddHabitacion = "http://localhost:3000/habitacion/crear"